version: "3.1"
services:
  node1:
    image: planaria/bitsim:0.0.2
    ports:
      - "18332-18333:18332-18333"
      - "18444:18444"
    environment:
      - N_PEERS=3
  node2:
    image: planaria/bitsim:0.0.2
    ports:
      - "17332-17333:18332-18333"
      - "17444:18444"
    environment:
      - N_PEERS=3
  node3:
    image: planaria/bitsim:0.0.2
    ports:
      - "16332-16333:18332-18333"
      - "16444:18444"
    environment:
      - N_PEERS=3
